#attnet = 100epochs
#minet, MInet = 50 epochs

General:
  log_dir: logs
  log_per_step: 1000
  seed: 1
  batch_size: 1
  results_dir: results
  data_dir: data

Data:
  elephant:
    input_dim: 230
    path: elephant_100x100_matlab.mat
    Models:
      minet:
        lr: 0.0001
        weight_decay: 0.005
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/elephant/minet
        pooling_mode: max #max, lse, ave
      MI_net:
        lr: 0.0001
        weight_decay: 0.005
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/elephant/MI_net
        pooling_mode: max #max, lse, ave
      attnet:
        lr: 0.0001
        weight_decay: 0.005
        momentum: 0.9
        nesterov: False
        criterion: neg-log-likelihood
        ckpt_dir: checkpoint/elephant/attnet
      sa_abmilp:
        lr: 0.0001
        weight_decay: 0.005
        momentum: 0.9
        nesterov: False
        criterion: neg-log-likelihood
        ckpt_dir: checkpoint/elephant/attnet
      flvnet:
        lr: 0.0001
        weight_decay: 0.005
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/elephant/flvnet
        pooling_mode: max #max, lse, ave
  fox:
    input_dim: 230
    path: fox_100x100_matlab.mat
    Models:
      minet:
        lr: 0.0001
        weight_decay: 0.01
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/fox/minet
        pooling_mode: max #max, lse, ave
      MI_net:
        lr: 0.0001
        weight_decay: 0.01
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/fox/MI_net
        pooling_mode: max #max, lse, ave
      attnet:
        lr: 0.0005
        weight_decay: 0.005
        momentum: 0.9
        nesterov: False
        criterion: neg-log-likelihood
        ckpt_dir: checkpoint/fox/attnet
      sa_abmilp:
        lr: 0.0005
        weight_decay: 0.005
        momentum: 0.9
        nesterov: False
        criterion: neg-log-likelihood
        ckpt_dir: checkpoint/fox/attnet
      flvnet:
        lr: 0.0005
        weight_decay: 0.005
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/fox/flvnet
        pooling_mode: max #max, lse, ave
  tiger:
    input_dim: 230
    path: tiger_100x100_matlab.mat
    Models:
      minet:
        lr: 0.0005
        weight_decay: 0.005
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/tiger/minet
        pooling_mode: max #max, lse, ave
      MI_net:
        lr: 0.0005
        weight_decay: 0.005
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/tiger/MI_net
        pooling_mode: max #max, lse, ave
      attnet:
        lr: 0.0001
        weight_decay: 0.01
        momentum: 0.9
        nesterov: False
        criterion: neg-log-likelihood
        ckpt_dir: checkpoint/tiger/attnet
      sa_abmilp:
        lr: 0.0001
        weight_decay: 0.01
        momentum: 0.9
        nesterov: False
        criterion: neg-log-likelihood
        ckpt_dir: checkpoint/tiger/attnet
      flvnet:
        lr: 0.0001
        weight_decay: 0.01
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/tiger/flvnet
        pooling_mode: max #max, lse, ave
  musk1:
    input_dim: 166
    path: musk1.mat
    Models:
      minet:
        lr: 0.0005
        weight_decay: 0.005
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/musk1/minet
        pooling_mode: max #max, lse, ave
      MI_net:
        lr: 0.0005
        weight_decay: 0.005
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/musk1/MI_net
        pooling_mode: max #max, lse, ave
      attnet:
        lr: 0.0005
        weight_decay: 0.005
        momentum: 0.9
        nesterov: False
        criterion: neg-log-likelihood
        ckpt_dir: checkpoint/musk1/attnet
      sa_abmilp:
        lr: 0.0005
        weight_decay: 0.005
        momentum: 0.9
        nesterov: False
        criterion: neg-log-likelihood
        ckpt_dir: checkpoint/musk1/attnet
      flvnet:
        lr: 0.0005
        weight_decay: 0.005
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/musk1/flvnet
        pooling_mode: max #max, lse, ave
  musk2:
    input_dim: 166
    path: musk2.mat
    Models:
      minet:
        lr: 0.0005
        weight_decay: 0.03
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/musk2/minet
        pooling_mode: max #max, lse, ave
      MI_net:
        lr: 0.0005
        weight_decay: 0.03
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/musk2/MI_net
        pooling_mode: max #max, lse, ave
      attnet:
        lr: 0.0005
        weight_decay: 0.03
        momentum: 0.9
        nesterov: False
        criterion: neg-log-likelihood
        ckpt_dir: checkpoint/musk2/attnet
      sa_abmilp:
        lr: 0.0005
        weight_decay: 0.03
        momentum: 0.9
        nesterov: False
        criterion: neg-log-likelihood
        ckpt_dir: checkpoint/musk2/attnet
      flvnet:
        lr: 0.0005
        weight_decay: 0.03
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/musk2/flvnet
        pooling_mode: max #max, lse, ave
  messidor:
    input_dim: 687
    path: messidor.mat
    Models:
      minet:
        lr: 0.0005
        weight_decay: 0.001
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/messidor/minet
        pooling_mode: max #max, lse, ave
      MI_net:
        lr: 0.0005
        weight_decay: 0.001
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/messidor/MI_net
        pooling_mode: max #max, lse, ave
      attnet:
        lr: 0.0005
        weight_decay: 0.001
        momentum: 0.9
        nesterov: False
        criterion: neg-log-likelihood
        ckpt_dir: checkpoint/messidor/attnet
        # weight_std: 0.05
      sa_abmilp:
        lr: 0.0005
        weight_decay: 0.001
        momentum: 0.9
        nesterov: False
        criterion: neg-log-likelihood
        ckpt_dir: checkpoint/messidor/attnet
        # weight_std: 0.05
      flvnet:
        lr: 0.0005
        weight_decay: 0.001
        momentum: 0.9
        nesterov: False
        criterion: binary-cross-entropy
        ckpt_dir: checkpoint/messidor/flvnet
        pooling_mode: max #max, lse, ave